"""--------INIT MODULE---------"""


from trytond.pool import Pool


from . import (account_dunning, collection,
               conector, conector_log, cron, currency,
               email_, exogena, line,
               pay_mode, payment_bank, payment_term,
               product, report,
               stock, wiz)


def register():
    """Function that register model view, wizard and reports with pool"""
    Pool.register(collection.Tracking,
                  conector.Actualizacion,
                  conector.Email,
                  conector.ImportedDocument,
                  conector_log.ConectorLog,
                  currency.Cron,
                  currency.CurrencyRate,
                  cron.Cron,
                  email_.Email,
                  line.Line,
                  pay_mode.VoucherPayMode,
                  payment_bank.PaymentBankGroupStart,
                  payment_bank.AccountBankParty,
                  payment_bank.BankPayment,
                  payment_term.PaymentTerm,
                  product.Product,
                  product.ProductCategory,
                  product.CategoryAccount,
                  product.Template,
                  product.CostPriceRevision,
                  report.PayrollExportStart,
                  report.CDSSaleIncomeDailyStart,
                  stock.Configuration,
                  stock.Location,
                  stock.ShipmentInternal,
                  stock.ShipmentDetailedStart,
                  stock.WarehouseKardexStockStartCds,
                  stock.MoveCDT,
                  stock.Inventory,
                  wiz.CreateAdjustmentNotesParameters,
                  wiz.AddCenterOperationLineP,
                  wiz.DocumentsForImportParameters,
                  wiz.DeleteVoucherTecnoStart,
                  wiz.MarkImportMultiStart,
                  wiz.FixBugsConectorView,
                  wiz.DeleteLiquidationStart,
                  wiz.DeleteEventLiquidationStart,
                  module='conector',
                  type_='model')

    Pool.register(account_dunning.DunningForceDraft,
                  conector.ImportedDocumentWizard,
                  conector_log.DeleteImportRecords,
                  payment_bank.PaymentBankGroup,
                  report.PayrollExport,
                  report.CDSSaleIncomeDaily,
                  stock.ModifyCostPrice,
                  stock.WarehouseKardexStockCds,
                  wiz.DeleteVoucherTecno,
                  wiz.VoucherMoveUnreconcile,
                  wiz.DeleteAccountType,
                  wiz.CheckImportedDoc,
                  wiz.MarkImportMulti,
                  wiz.MoveFixParty,
                  wiz.ForceDraftVoucher,
                  wiz.UnreconcilieMulti,
                  wiz.CreateAdjustmentNotes,
                  wiz.AddCenterOperationLine,
                  wiz.ReimportExcepcionDocument,
                  wiz.DocumentsForImport,
                  wiz.ConfirmLinesBankstatement,
                  wiz.GroupMultirevenueLines,
                  wiz.GroupDatafonoLines,
                  wiz.FixBugsConector,
                  wiz.DeleteLiquidation,
                  wiz.DeleteEventLiquidation,
                  module='conector',
                  type_='wizard')

    Pool.register(collection.PortfolioStatusReport,
                  exogena.TemplateExogena,
                  exogena.F1001,
                  exogena.F1003,
                  exogena.F1005,
                  exogena.F1006,
                  exogena.F1007,
                  exogena.F1008,
                  exogena.F1009,
                  exogena.F1011,
                  exogena.F1012,
                  exogena.F1043,
                  exogena.F1045,
                  exogena.F2015,
                  exogena.F2276,
                  exogena.F5247,
                  exogena.F5248,
                  exogena.F5249,
                  exogena.F5250,
                  exogena.F5251,
                  exogena.F5252,
                  payment_bank.PaymentBankGroupReport,
                  payment_bank.BankReportBancolombia,
                  report.PayrollExportReport,
                  report.CDSSaleIncomeDailyReport,
                  report.LoanFormatReport,
                  stock.ShipmentDetailedReport,
                  stock.WarehouseCdsKardexReport,
                  stock.WarehouseReport,
                  module='conector',
                  type_='report')
