"""--------INIT MODULE---------"""

from trytond.pool import Pool


from . import (account, account_dunning, collection,
               conector, conector_log, configuration, cron, currency,
               email_, exogena, line,
               pay_mode, payment_bank, payment_term,
               permissions, product, production, purchase, report,
               sale, sale_device, stock, tax, wiz)


def register():
    """Function that register model view, wizard and reports with pool"""
    Pool.register(account.Account,
                  account.Move,
                  account.MoveLine,
                  account.BalanceStockStart,
                  account.BankMoneyTransferStart,
                  account.AnalyticAccountEntry,
                  account.MoveCloseYearStart,
                  account.PartyWithholdingStart,
                  account.Period,
                  account.Reconciliation,
                  account.AuxiliaryPartyStart,
                  account.AccountAsset,
                  account.AuxiliaryBookStartCDS,
                  account.IncomeStatementView,
                  collection.Tracking,
                  conector.Actualizacion,
                  conector.Email,
                  conector.ImportedDocument,
                  conector_log.ConectorLog,
                  currency.Cron,
                  currency.CurrencyRate,
                  cron.Cron,
                  email_.Email,
                  line.Line,
                  pay_mode.VoucherPayMode,
                  payment_bank.PaymentBankGroupStart,
                  payment_bank.AccountBankParty,
                  payment_bank.BankPayment,
                  payment_term.PaymentTerm,
                  permissions.Permissions,
                  permissions.LinePermissions,
                  product.Product,
                  product.ProductCategory,
                  product.CategoryAccount,
                  product.Template,
                  product.CostPriceRevision,
                  production.Production,
                  production.ProductionDetailedStart,
                  purchase.Configuration,
                  purchase.Purchase,
                  purchase.PurchaseLine,
                  report.PayrollExportStart,
                  report.CDSSaleIncomeDailyStart,
                  sale.Sale,
                  sale.Statement,
                  sale_device.SaleDevice,
                  sale_device.Journal,
                  sale.SaleShopDetailedCDSStart,
                  sale.SaleInvoiceValueCdstStart,
                  stock.Configuration,
                  stock.Location,
                  stock.ShipmentInternal,
                  stock.ShipmentDetailedStart,
                  stock.WarehouseKardexStockStartCds,
                  stock.MoveCDT,
                  stock.Inventory,
                  tax.Tax,
                  tax.MiddleModel,
                  tax.TaxRuleLine,
                  tax.TaxesConsolidationStart,
                  wiz.CreateAdjustmentNotesParameters,
                  wiz.AddCenterOperationLineP,
                  wiz.DocumentsForImportParameters,
                  wiz.DeleteVoucherTecnoStart,
                  wiz.MarkImportMultiStart,
                  wiz.FixBugsConectorView,
                  wiz.DeleteLiquidationStart,
                  wiz.DeleteEventLiquidationStart,
                  module='conector',
                  type_='model')

    Pool.register(account.BalanceStock,
                  account.BankMoneyTransfer,
                  account.PrintAuxiliaryBookCDS,
                  account.IncomeStatementWizard,
                  account.ActiveForceDraft,
                  account.PrintPartyWithholding,
                  account_dunning.DunningForceDraft,
                  account.MoveCloseYear,
                  conector.ImportedDocumentWizard,
                  conector_log.DeleteImportRecords,
                  payment_bank.PaymentBankGroup,
                  production.ProductionDetailed,
                  production.ProductionForceDraft,
                  report.PayrollExport,
                  report.CDSSaleIncomeDaily,
                  sale.SaleShopDetailedCDS,
                  sale.SaleInvoiceValueCdst,
                  stock.ModifyCostPrice,
                  stock.WarehouseKardexStockCds,
                  tax.TaxesConsolidation,
                  tax.PrintTaxesPostedAccumulated,
                  wiz.DeleteVoucherTecno,
                  wiz.VoucherMoveUnreconcile,
                  wiz.DeleteAccountType,
                  wiz.CheckImportedDoc,
                  wiz.MarkImportMulti,
                  wiz.MoveFixParty,
                  wiz.ForceDraftVoucher,
                  wiz.UnreconcilieMulti,
                  wiz.CreateAdjustmentNotes,
                  wiz.AddCenterOperationLine,
                  wiz.ReimportExcepcionDocument,
                  wiz.DocumentsForImport,
                  wiz.ConfirmLinesBankstatement,
                  wiz.GroupMultirevenueLines,
                  wiz.GroupDatafonoLines,
                  wiz.FixBugsConector,
                  wiz.DeleteLiquidation,
                  wiz.DeleteEventLiquidation,
                  module='conector',
                  type_='wizard')

    Pool.register(account.AuxiliaryParty,
                  account.AuxiliaryBookCDS,
                  account.IncomeStatementReport,
                  account.IncomeStatement,
                  account.TrialBalanceDetailedCds,
                  account.PartyWithholding,
                  collection.PortfolioStatusReport,
                  exogena.TemplateExogena,
                  exogena.F1001,
                  exogena.F1003,
                  exogena.F1005,
                  exogena.F1006,
                  exogena.F1007,
                  exogena.F1008,
                  exogena.F1009,
                  exogena.F1011,
                  exogena.F1012,
                  exogena.F1043,
                  exogena.F1045,
                  exogena.F2015,
                  exogena.F2276,
                  exogena.F5247,
                  exogena.F5248,
                  exogena.F5249,
                  exogena.F5250,
                  exogena.F5251,
                  exogena.F5252,
                  payment_bank.PaymentBankGroupReport,
                  payment_bank.BankReportBancolombia,
                  production.ProductionDetailedReport,
                  report.PayrollExportReport,
                  report.CDSSaleIncomeDailyReport,
                  report.LoanFormatReport,
                  sale.SaleShopDetailedCDSReport,
                  sale.SaleInvoiceValueCdstReport,
                  stock.ShipmentDetailedReport,
                  stock.WarehouseCdsKardexReport,
                  stock.WarehouseReport,
                  tax.TaxesPostedAccumulated,
                  module='conector',
                  type_='report')
