"""--------INIT MODULE---------"""

from trytond.pool import Pool
from . import conector
from . import party
from . import product
from . import sale
from . import sale_device
from . import configuration
from . import voucher
from . import pay_mode
from . import electronic_payroll_wizard
from . import company
from . import payment_term
from . import purchase
from . import stock
from . import invoice
from . import tax
from . import production
from . import wiz
from . import report
from . import account
from . import payroll
from . import cron
from . import statement
from . import payment_bank
from . import loan
from . import liquidation
from . import permissions
from . import currency
from . import account_dunning
from . import collection
from . import line


def register():
    """Function that register model view, wizard and reports with pool"""
    Pool.register(account.Account,
                  account.Move,
                  account.MoveLine,
                  account.BalanceStockStart,
                  account.AnalyticAccountEntry,
                  account.PartyWithholdingStart,
                  account.Reconciliation,
                  account.AuxiliaryPartyStart,
                  account.AccountAsset,
                  account.AuxiliaryBookStartCDS,
                  account.IncomeStatementView,
                  company.Company,
                  conector.Actualizacion,
                  conector.ImportedDocument,
                  conector.ConectorLog,
                  configuration.Configuration,
                  currency.Cron,
                  currency.CurrencyRate,
                  cron.Cron,
                  invoice.Invoice,
                  invoice.InvoiceLine,
                  invoice.UpdateInvoiceTecnoStart,
                  loan.Loan,
                  line.Line,
                  pay_mode.VoucherPayMode,
                  payment_bank.PaymentBankGroupStart,
                  payment_bank.AccountBankParty,
                  payment_bank.BankPayment,
                  payment_term.PaymentTerm,
                  payroll.Bank,
                  payroll.WageType,
                  payroll.PayrollPaymentStartBcl,
                  payroll.StaffEvent,
                  payroll.Payroll,
                  payroll.PayslipSendStart,
                  payroll.Liquidation,
                  payroll.LiquidationPaymentStartBcl,
                  payroll.SettlementSendStart,
                  payroll.PayrollElectronic,
                  payroll.StaffAccessRests,
                  payroll.StaffAccess,
                  payroll.PayrollLine,
                  payroll.ImportBiometricRecordsParameters,
                  payroll.CertificateOfIncomeAndWithholdingSendStart,
                  payroll.StaffAccessView,
                  payroll.PayrollIBCView,
                  payroll.PayrollElectronicCDS,
                  payroll.LineLiquidationEvent,
                  party.CheckVIESResult,
                  party.Party,
                  party.PartyAddress,
                  party.ContactMechanism,
                  permissions.Permissions,
                  permissions.LinePermissions,
                  product.Product,
                  product.ProductCategory,
                  product.Template,
                  production.Production,
                  production.ProductionDetailedStart,
                  purchase.Configuration,
                  purchase.Purchase,
                  purchase.PurchaseLine,
                  report.PayrollExportStart,
                  report.CDSSaleIncomeDailyStart,
                  sale.Sale,
                  sale.SaleLine,
                  sale.Statement,
                  sale_device.SaleDevice,
                  sale_device.Journal,
                  sale.SaleShopDetailedCDSStart,
                  statement.BankStatement,
                  statement.BankStatementLine,
                  statement.BankStatementBankLine,
                  statement.BankStatementLineRelation,
                  statement.CreateBankLineParameters,
                  statement.StatementLine,
                  stock.Location,
                  stock.ShipmentInternal,
                  stock.WarehouseKardexStockStartCds,
                  stock.MoveCDT,
                  stock.Inventory,
                  tax.Tax,
                  tax.MiddleModel,
                  tax.TaxRuleLine,
                  tax.TaxesConsolidationStart,
                  voucher.Voucher,
                  voucher.MultiRevenue,
                  voucher.Note,
                  voucher.VoucherConfiguration,
                  wiz.CreateAdjustmentNotesParameters,
                  wiz.AddCenterOperationLineP,
                  wiz.DocumentsForImportParameters,
                  wiz.DeleteVoucherTecnoStart,
                  wiz.MarkImportMultiStart,
                  wiz.FixBugsConectorView,
                  wiz.DeleteLiquidationStart,
                  wiz.DeleteEventLiquidationStart,
                  module='conector',
                  type_='model')

    Pool.register(account.BalanceStock,
                  account.PrintAuxiliaryBookCDS,
                  account.IncomeStatementWizard,
                  account.ActiveForceDraft,
                  account.PrintPartyWithholding,
                  account_dunning.DunningForceDraft,
                  conector.ImportedDocumentWizard,
                  electronic_payroll_wizard.PayrollElectronicCdst,
                  invoice.UpdateInvoiceTecno,
                  invoice.UpdateNoteDate,
                  invoice.CreditInvoice,
                  loan.LoanForceDraft,
                  party.CheckVIES,
                  payment_bank.PaymentBankGroup,
                  payroll.PayrollPaymentBcl,
                  payroll.PayslipSend,
                  payroll.LiquidationPaymentBcl,
                  payroll.SettlementSend,
                  payroll.SendCertificateOfIncomeAndWithholding,
                  payroll.ImportBiometricRecords,
                  payroll.StaffAccessWizard,
                  payroll.PayrollIBCWizard,
                  production.ProductionDetailed,
                  production.ProductionForceDraft,
                  report.PayrollExport,
                  report.CDSSaleIncomeDaily,
                  sale.SaleShopDetailedCDS,
                  stock.ModifyCostPrice,
                  stock.WarehouseKardexStockCds,
                  statement.StatementMoveValidate,
                  statement.CreateBankLine,
                  tax.TaxesConsolidation,
                  wiz.DeleteVoucherTecno,
                  wiz.VoucherMoveUnreconcile,
                  wiz.DeleteImportRecords,
                  wiz.DeleteAccountType,
                  wiz.CheckImportedDoc,
                  wiz.MarkImportMulti,
                  wiz.MoveFixParty,
                  wiz.ForceDraftVoucher,
                  wiz.UnreconcilieMulti,
                  wiz.CreateAdjustmentNotes,
                  wiz.AddCenterOperationLine,
                  wiz.ReimportExcepcionDocument,
                  wiz.DocumentsForImport,
                  wiz.ConfirmLinesBankstatement,
                  wiz.GroupMultirevenueLines,
                  wiz.GroupDatafonoLines,
                  wiz.FixBugsConector,
                  wiz.DeleteLiquidation,
                  wiz.DeleteEventLiquidation,
                  module='conector',
                  type_='wizard')

    Pool.register(account.AuxiliaryParty,
                  account.AuxiliaryBookCDS,
                  account.IncomeStatementReport,
                  account.TrialBalanceDetailedCds,
                  account.PartyWithholding,
                  collection.PortfolioStatusReport,
                  liquidation.LiquidationReport,
                  payment_bank.PaymentBankGroupReport,
                  payment_bank.BankReportBancolombia,
                  payroll.PayrollPaymentReportBcl,
                  payroll.LiquidationPaymentReportBcl,
                  payroll.PayrollReport,
                  payroll.PayrollExo2276,
                  payroll.StaffAccessReport,
                  payroll.PayrollIBCReport,
                  payroll.PayrollPaycheckReportExten,
                  production.ProductionDetailedReport,
                  report.PayrollExportReport,
                  report.CDSSaleIncomeDailyReport,
                  report.LoanFormatReport,
                  sale.SaleShopDetailedCDSReport,
                  stock.ShipmentDetailedReport,
                  stock.WarehouseCdsKardexReport,
                  module='conector',
                  type_='report')
